baseURL = 'https://docs.bizzkit.com/'
title = 'Bizzkit Documentation'

theme = ['docsy']

# Language settings
contentDir = 'content/en'
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false
enableMissingTranslationPlaceholders = true

[menu]
[[menu.main]]
  name = "Documentation"
  weight = 10
  url = "/docs/latest/home"

# Language configuration
[languages]
  [languages.en]
    title = 'Hugo Playground'
    description = 'Bizzkit Documentation'
    languageName ='English'
    weight = 1
  [languages.da]
    title = "Hugo Legeplads"
    description = "Bizzkit Dokumentation"
    languageName ="Dansk"
    contentDir = "content/da"
    weight = 2
    [languages.da.params]
      # See: https://gohugohq.com/howto/hugo-dateformat/#conclusion-table
      time_format_default = "02.01.2006"
      time_format_blog = "02.01.2006"
      language_alternatives = ["en"]

# Markdown interpreter settings
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      # Enables use of inline HTML and JavaScript - we control the content, so we can trust it
      unsafe = true
  [markup.highlight]
      # See: https://xyproto.github.io/splash/docs/all.html
      style = "dracula"

[params]
copyright = "Kasper Schultz Davidsen"
version_menu = "Releases"
version = "0.1"

[[params.versions]]
fullversion = "v0.1.0"
version = "latest"
githubbranch = "v0.1.0"
docsbranch = "main"
url = "/docs/latest/home"

[[params.versions]]
fullversion = "v0.0.0"
version = "v0.0"
githubbranch = "v0.0.0"
docsbranch = "release-v0.0.0"
url = "/docs/v0.0/home"
