baseURL = 'https://docs.bizzkit.com/'
title = 'Bizzkit Documentation'

theme = ['docsy']

enableRobotsTXT = true
enableGitInfo = true

# Language settings
contentDir = 'content/en'
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false
enableMissingTranslationPlaceholders = true

[menu]
[[menu.main]]
  name = "Documentation"
  weight = 10
  url = "/docs/latest"

[[menu.main]]
    name = "GitHub"
    weight = 100
    url = "https://github.com/Xitric/hugo-playground/"
    pre = "<i class='fab fa-github'></i>"

[services]
[services.googleAnalytics]
id = "UA-00000000-0"

# Language configuration
[languages]
  [languages.en]
    title = 'Hugo Playground'
    description = 'Bizzkit Documentation'
    languageName ='English'
    weight = 1
  [languages.da]
    title = "Hugo Legeplads"
    description = "Bizzkit Dokumentation"
    languageName ="Dansk"
    contentDir = "content/da"
    weight = 2
    [languages.da.params]
      # See: https://gohugohq.com/howto/hugo-dateformat/#conclusion-table
      time_format_default = "02.01.2006"
      time_format_blog = "02.01.2006"
      language_alternatives = ["en"]

# Markdown interpreter settings
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      # Enables use of inline HTML and JavaScript - we control the content, so we can trust it
      unsafe = true
  [markup.highlight]
      # See: https://xyproto.github.io/splash/docs/all.html
      style = "friendly"

[params]
copyright = "Kasper Schultz Davidsen"
version_menu = "Releases"

# TODO: May need to replace with something better, that takes the selected version into account
# Azure Static Web Apps and Cognitive Services may provide something of value
offlineSearch = true
offlineSearchSummaryLength = 70
offlineSearchMaxResults = 10

[params.ui]
sidebar_search_disable = false

[params.ui.feedback]
# TODO: Can be extended to provide options for letting users enter their feedback anonymously
enable = true

[params.ui.readingtime]
enable = true

[params.links]
[[params.links.user]]
  name = "Hugo documentation"
  url = "https://gohugo.io/documentation/"
  desc = "Hugo documentation"
[[params.links.user]]
  name = "Docsy documentation"
  url = "https://www.docsy.dev/docs/"
  desc = "Docsy documentation"
[[params.links.developer]]
  name = "Kubernetes reference"
  url = "https://github.com/kubernetes/website"
  desc = "Reference Hugo website for Kubernetes"
[[params.links.developer]]
  name = "Thanos reference"
  url = "https://github.com/thanos-io/thanos/tree/main/website"
  desc = "Reference Hugo website for Thanos"
[[params.links.developer]]
	name = "GitHub"
	url = "https://github.com/Xitric/hugo-playground/"
	icon = "fab fa-github"
  desc = "Development takes place here!"

# Automatically convert embedded plantuml into UML diagrams!
[params.plantuml]
enable = true
theme = "superhero"
svg_image_url = "https://www.plantuml.com/plantuml/svg/"

[[params.versions]]
fullversion = "v0.1.0"
version = "latest"
githubbranch = "v0.1.0"
docsbranch = "main"
url = "/docs/latest"

[[params.versions]]
fullversion = "v0.0.0"
version = "v0.0"
githubbranch = "v0.0.0"
docsbranch = "release-v0.0.0"
url = "/docs/v0.0"
